### ISSUE TITLE
Unable to ingest PDFs from Oregon Digital

### ISSUE THREAD

**Issue by erastovich** [uoregon-libraries/digital-exhibits-spotlight#52] opened 2019-07-18 16:54 UTC
PDFs from Oregon Digital do not upload into Spotlight. I tried by single upload and list of OregonDigital IDs and neither worked

**Comment by mfgaede** [comment] 2019-08-15 17:25
Duplicate of #18 
Duplicate of #25

**Closed** 2019-09-06 20:34 UTC
Labels: duplicate, priority
